services:
  frontend:
    build:
      context: .
      target: "${TARGET:-prod}"
      args:
        - SRV_GROUP_ID=${SRV_GROUP_ID}
    container_name: frontend
    hostname: frontend.lan
    group_add:
      - srv
    networks:
      - infra
    volumes:
      - "frontend_wwwroot:/app/www"
      - "frontend_certs:/app/certs"
    stop_signal: SIGKILL

volumes:
  frontend_wwwroot:
    external: true
  frontend_certs:
    external: true

networks:
  infra:
    external: true
