services:
  frontend:
    build:
      context: .
      target: "${TARGET:-prod}"
    container_name: frontend
    hostname: frontend.lan
    group_add:
      - srv
    networks:
      - infra
    volumes:
      - "frontend_wwwroot:/var/www"
      - "frontend_certs:/app/certs"
    stop_signal: SIGKILL

volumes:
  frontend_wwwroot:
    external: true
  frontend_certs:
    external: true

networks:
  infra:
    external: true
